### ISSUE TITLE
0B_readsector stuck after EMMC: Sending command 33220010 arg 00000000

### ISSUE THREAD

**Issue by ptrk8** [bztsrc/raspi3-tutorial#110]
I'm using a [64GB SanDisk Extreme Pro microSD card](https://www.westerndigital.com/products/memory-cards/sandisk-extreme-pro-uhs-i-microsd#SDSQXCU-064G-GN6MA), which is a class 10 card and appears to work well with Raspberry Pi 3s according to [this list](https://elinux.org/RPi_SD_cards).

Unfortunately, when I run the `0B_readsector` example on my Raspberry Pi 3 Model B+, it fails to finish initialising the SD card and gets stuck at the following stage of the `sd_init()` function:

```
EMMC: GPIO set up
EMMC: reset OK
sd_clk divisor 00000068, shift 00000006
EMMC: Sending command 00000000 arg 00000000
EMMC: Sending command 08020000 arg 000001AA
EMMC: Sending command 37000000 arg 00000000
EMMC: Sending command 29020000 arg 51FF8000
EMMC: CMD_SEND_OP_COND returned VOLTAGE CCS 0000000040F98000
EMMC: Sending command 37000000 arg 00000000
EMMC: Sending command 29020000 arg 51FF8000
EMMC: CMD_SEND_OP_COND returned COMPLETE VOLTAGE CCS FFFFFFFFC1F98000
EMMC: Sending command 02010000 arg 00000000
EMMC: Sending command 03020000 arg 00000000
EMMC: CMD_SEND_REL_ADDR returned FFFFFFFFAAAA0000
sd_clk divisor 00000002, shift 00000000
EMMC: Sending command 07030000 arg AAAA0000
EMMC: Sending command 37020000 arg AAAA0000
EMMC: Sending command 33220010 arg 00000000
```

What's the best way to debug this issue and is the `0B_readsector` example supposed to work for my SD card?

**Comment by bztsrc** [comment]
> supposed to work for my SD card?

I never had this kind of card, so I honestly don't know. It should I suppose.

> What's the best way to debug this issue

First, use a different card. See what hex values are printed on screen. Then try this card, and compare what hex values are different. The commands, arguments and the responses should be the same, but if any of them differ, that will give you a clue.

Try to locate which loop stops the execution. If it's not printed, then print the register's value it is checking.

Hope this helps.
bzt
