### ISSUE TITLE
Tutorial 9: Framebuffer works only in qemu

### ISSUE THREAD

**Issue by sedrubal** [bztsrc/raspi3-tutorial#22]
For me the [tutorial 9: Framebuffer](https://github.com/bztsrc/raspi3-tutorial/tree/master/09_framebuffer) works only in qemu but the screen is black, when I test it on the real hardware. When I add some Instructions in the for loops, that fill the buffer (e.g. `wait_cycles(0);`) it works. Is it possible that we have to wait for some kind of ack until we can write the next pixel? Can you provide some more docs about the framebuffer?

Btw.: thanks for this tutorial. It is great :wink:

**Comment by bztsrc** [comment]
Interesting. I've tested it on real hw, worked like a charm.
I don't think wait cycles is the answer. The point is quite the contrary, put as much pixel as you can to improve FPS. I've used the BCM manual and the tutorials I linked, so I'm afraid I can't give you more docs than I already have given.
