### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#23]
I would just like to know what you would like me to do with the licence that you have at the top of your files. I have heavily modified most of your code and added my own so I am unsure how to reference your work. Here is my [GitHub repo](https://github.com/OllieLollie1/Raspi3-Kernel) where the code is. Sorry I'm still a high school student and I don't have any experience with code referencing.

**Comment by bztsrc** [comment]
Hi,

As for the license, you can read it here: https://github.com/bztsrc/raspi3-tutorial/blob/master/LICENSE
    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use, copy,
    modify, merge, publish, distribute, sublicense, and/or sell copies
    of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

You can use the code for your own purposes, attribution would be appreciated, but not mandatory.

Cheers,
bzt
