### ISSUE TITLE
Static buffers for fat.c

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#24]
I have mostly gotten static buffers for fat.c however I have been unable to understand the fat_readfile() function because of the fat32 and fat16 selection. I see that you do read from them and therefore their contents it important. I am trying to do this because it messes with my malloc like function which uses the _end marker. Please help me understand that piece of code.

**Comment by bztsrc** [comment]
Well, I use the same code for both fat16 and fat32. The only difference is that I get the same initial values from different fields for fat32, see fat.c line 116.
root_sec: starting sector of root directory
data_sec: starting sector of data area (cluster 2 in other words)

Later when the file allocation table is parsed, I either use 16 bit wide ints (for fat16) or 32 bits wide ints (for fat32) as the elements of the table, see line 161. That's all, everything else is the same. I made the distintion by checking the 16 bits long version of sector per fat: (bpb->spf16?bpb->spf16:bpb->spf32). If it's zero, then it must be a fat32, see line 167 for example. I also dump all the important variables used in calculations at line 180.

If you want to better understand what sector positions are calculated and why, I suggest to read Microsoft's documentation on the FAT filesystem. The wikipedia's article is also a good start, as it has a figure illustrating the regions on the disk. They are the same, save that root directory is included in data area for FAT32 (hence the checks in lines 123 and 173).

Hope this helps. Cheers,
bzt
