### ISSUE TITLE
Emulation of stock raspbian image

### ISSUE THREAD

**Issue by Lindenk** [bztsrc/raspi3-tutorial#28]
Hey!

First off, you are doing amazing work here. These tutorials are pretty amazing.

So, I'd like to be able to emulate the stock raspbian for some testing but I can't seem to get any output. 

I've attempted copying out the dtb and kernel from the image and running:

```
qemu-system-aarch64 -M raspi3 -drive file=2018-04-18-raspbian-stretch-lite.img,if=sd,format=raw

qemu-system-aarch64 -M raspi3 -drive file=2018-04-18-raspbian-stretch-lite.img,if=sd,format=raw -dtb bcm2710-rpi-3-b-plus.dtb -append "root=/dev/mmcblk0p2" -kernel kernal7.img

qemu-system-aarch64 -M raspi3 -sd 2018-04-18-raspbian-stretch-lite.img -dtb bcm2710-rpi-3-b-plus.dtb -append "root=/dev/mmcblk0p2" -kernel rpi_raspbian_kernal7.img
```

along with several other random attempts. However, nothing I seem to do produces any output either using `-nographic`, or over vnc.

Any sugguestions?

**Comment by bztsrc** [comment]
Sorry, I don't think qemu is good enough to emulate raspbian. The thing is, my patch only adds support for booting AArch64 kernels, but it does not add support for BCM hardware, like the System Timer (and thus makes the kernel's delay loop hang). I can imagine you can compile a special linux kernel for qemu, but right now qemu is mostly for developers writing their own, minimal barebone applications.
