### ISSUE TITLE
Issue about mailbox message

### ISSUE THREAD

**Issue by lizhuohua** [bztsrc/raspi3-tutorial#3]
https://github.com/bztsrc/raspi3-tutorial/blob/a7b01cca16226177e8f71ec2457045e2b4bcb70c/04_mailboxes/main.c#L39
If `mbox[3] = 0`, I always got result 0.
If I set `mbox[3] = 8`, it works like a charm.

**Comment by bztsrc** [comment]
Hi,

Thank you for trying out my tutorials and reporting issues! I really appreciate that! I've fixed this too.
