### ISSUE TITLE
Use CC variable on Makefiles instead of hardcoded aarch64-elf-gcc

### ISSUE THREAD

**Issue by cirosantilli** [bztsrc/raspi3-tutorial#30]
This allows people to just:

```
sudo apt-get install gcc-aarch64-linux-gnu
```

which will greatly reduce the barrier of entry and make you more famous.

But first we should factor out all those identical makefiles into one on toplevel /Makefile and symlink into each directory.

Since I am lazy I just did a sed for now for my own use: https://github.com/cirosantilli/raspi3-tutorial/commit/df31015b2f9aa930e28796e586bda32fe488d2dd

```
find . -name Makefile | xargs sed -i 's/aarch64-elf-/aarch64-linux-gnu-/'
```

**Comment by bztsrc** [comment]
Thanks, but no. Compiling your own cross-compiler is part of the learning curve.
