### ISSUE TITLE
add a make run target to each Makefile

### ISSUE THREAD

**Issue by cirosantilli** [bztsrc/raspi3-tutorial#32]
Allow users to do just `make run` and get everything running, compiles and runs, it's beautiful.

Also semi blocked on factoring makefiles: https://github.com/bztsrc/raspi3-tutorial/issues/30

**Comment by bztsrc** [comment]
Well, the examples are supposed to be run on a real hardware. Some of them will never ever run in emulator, like the power management tutorial or the Raspbootin64. Regardless it sounds like a good thing to have, so I've added `run` rules to the Makefiles.
