### ISSUE TITLE
How to build cross toolchain with crosstool-ng

### ISSUE THREAD

**Issue by cirosantilli** [bztsrc/raspi3-tutorial#35]
Just to remind myself and others in the future: the following worked:

- this repo: 9e5611a624b3037788d5b29d951304938bff13ea
- ct-ng: ab3c204aee88f08481f1f63825d0e94b082ef84e

On `ct-ng menuconfig`, set:

- arch: arm64
- OS: bare metal

Then build. Tested on tutorial 05.

**Comment by bztsrc** [comment]
Hey, thanks!
