### ISSUE TITLE
FPU coprocessor

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#39]
I read the README in the printf tutorials and you said that you had to enable the FPU coprocessor however I didn't actually see a chunk of code in start.s that did this. I wanted the coprocessor online because i'm trying to do bare metal SLAM and I need double types to work. How do you bring the coprocessor online? and as a side note apart from clearing the bss is your start.s acceptable for multi core?

**Comment by OllieLollie1** [comment]
I found it sorry

**Comment by bztsrc** [comment]
No worries :-)
