### ISSUE TITLE
Printf malloc

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#40]
In the printf tutorials you say because you don't have malloc you simply place the string after the code. How much would you need to malloc if you had that ability?

**Comment by bztsrc** [comment]
You need a sufficiently big enough buffer. Depends on what you want to write.
If you also have a vnsprintf implementation, you can use the trick mentioned in the `sprintf man page` under the section EXAMPLE:
```c
// To allocate a sufficiently large string and print into it (code correct for both glibc 2.0
// and glibc 2.1):

       #include <stdio.h>
       #include <stdlib.h>
       #include <stdarg.h>

       char *
       make_message(const char *fmt, ...)
       {
           int size = 0;
           char *p = NULL;
           va_list ap;

           /* Determine required size */

           va_start(ap, fmt);
           size = vsnprintf(p, size, fmt, ap);
           va_end(ap);

           if (size < 0)
               return NULL;

           size++;             /* For '\0' */
           p = malloc(size);
           if (p == NULL)
               return NULL;

           va_start(ap, fmt);
           size = vsnprintf(p, size, fmt, ap);
           va_end(ap);

           if (size < 0) {
               free(p);
               return NULL;
           }

           return p;
       }
```
Another possibility to implement printf in a way to output each and every character right on the spot, therefore no memory allocation needed at all. I've used sprintf to show you how it's done, and it was obvious to reuse that code for printf. But that's not the only way.

**Comment by OllieLollie1** [comment]
Just as a side note would you mind having a look at my post on the pi forums about audio please?

**Comment by OllieLollie1** [comment]
I finished a way to malloc memory for printf it is in my github repo if you wanted to look at it. I was unable to find how circle does audio so would you please check out this post: https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=212930&sid=aeafdbf5f08d4d0563e61392c6cac157
