### ISSUE TITLE
EMMC Commands

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#46]
Where did you find the commands for the EMMC. I believe I have written a suitable function to write to the SD card but I don't know the hex values for the commands.

**Comment by bztsrc** [comment]
I've reverse engineered the sources I've found on the [raspberrypi.org forums](https://www.raspberrypi.org/forums/viewtopic.php?t=94133). Most notably LdB's tutorials and [this one](https://github.com/moizumi99/RPiHaribote/blob/master/haribote/sdcard.c).

Cheers,
bzt
