### ISSUE TITLE
AUX_MU_IIR_REG query

### ISSUE THREAD

**Issue by petemoore** [bztsrc/raspi3-tutorial#68]
Hi Zoltan,

Sorry to open a new issue, I couldn't work out a way to reopen the closed PR, but I still believe there is a mistake there. See https://github.com/bztsrc/raspi3-tutorial/pull/67#issuecomment-606017227.

Many thanks!
Pete

**Comment by bztsrc** [comment]
Thank you very much for your feedback.

As I've explained in the PR comments, even though it might not be needed on newer boards, there's no harm setting bits 6:7, and I for one have a board which requires those bits set to actually clear the FIFO queue.

Btw, I'd gladly merge a pull request for your comments, as I think they are good and correct.

Cheers,
bzt
