### ISSUE TITLE
Making Link to Isl

### ISSUE THREAD

**Issue by JayyCee** [bztsrc/raspi3-tutorial#7]
Thanks for the great tutorial!

Here's feedback for building the toolchain:

1. I had to use "make -j1", instead of "make -j4".  Otherwise, it stopped short due to errors.
2. I had to do "ln -s isl-0.18 isl" before "cd binutils-2.29".  Otherwise, the build process fails to find the isl source tree.

Again, thank you for your great work!

**Comment by bztsrc** [comment]
You are welcome!
Thanks for the contribution, maybe that will help other ubuntu users too. In make "-j" means the number of threads to run, it should be the number of your cores. It won't hurt if you put the isl symlink outside of binutils too, although seems odd.
