### ISSUE TITLE
Another method of getting an Aarch64 Cross-Compiler

### ISSUE THREAD

**Issue by AnikCandian** [bztsrc/raspi3-tutorial#73]
I believe there's another method of doing this, especially if you're using Windows. If you don't have "wget", can't you simply install the cross-compiler from ARM's developer site? When you reach the site, find "Aarch64 bare-metal target". Click the file name that resides under that header with the ending of ".xz". Download it and unzip it using something that can unzip compressed files (I use 7Zip for that). Put everything inside a folder, look at the bin folder, and that's where all the executables are.

There are several caveats to this. For one, there's slightly more steps by using this method than using the wget method. Also, you cannot run the executables by typing up its name in the command line. You have to execute it like an application (file.ending [options here]). I haven't tested this on a Mac yet.

If you are wondering about the link to the site, it's here.

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

**Comment by bztsrc** [comment]
Hi,

Thanks for the heads up. There are several problems with your suggestions though.

> Click the file name that resides under that header with the ending of ".xz".

Don't use ".xz", it is not safe and known to be vulnerable to transmission errors.

> Also, you cannot run the executables by typing up its name in the command line.

Then I see no way how these could be used from a Makefile.

However if you create a pull request with a "note: there's also... download here" paragraph added to the cross-compiler readme, I'll merge it!

Just for the records, if you don't have "wget", then you could use "curl".

Cheers,
bzt
