### ISSUE TITLE
Raspbootin64 does not work on Raspberry Pi 4

### ISSUE THREAD

**Issue by dascandy** [bztsrc/raspi3-tutorial#74]
MMIO_BASE is fixed to one value, needs to be 0xFE000000 for raspberry pi 4 and 0x3F000000 for raspberry pi 3 (variants).

**Comment by dascandy** [comment]
Pull request opened with proposed (and tested) fix.

**Comment by bztsrc** [comment]
Yes, this is intended. The multiplatform version is at https://gitlab.com/bztsrc/imgrecv/-/tree/master/raspi

Cheers,
bzt
