### ISSUE TITLE
Why not use the mini UART?

### ISSUE THREAD

**Issue by mrvn** [bztsrc/raspi3-tutorial#77]
I recently got a RPi4 and now tried running my original raspbootin on it in 32bit mode. But I can't seem to get any useful data over the mini UART. The firmware works fine but after start4.elf loads I only get garbage, as if the BAUD rate changes.

Is that the reason why you switched over to the PLL uart in raspbootin64?

**Comment by bztsrc** [comment]
Hi,

There can be many reasons. First, the UART clock is tied to the CPU clock, so to get constant baud rates, first you have to set a consistent freq for the UART (using a mailbox call). There has been changes regarding this as the board evolved (I'm not sure what's the status for RPi4, but there was definitely a change between RPi2 and RPi3), so it's the better to just always set the freq to a known value.

Then, I was told that GPIO header mapping goes a little bit different on the RPi4, so it could be that the UART is not connected to the pins 14/15 properly. Sadly I don't have an RPi4 to try this out.

> Is that the reason why you switched over to the PLL uart in raspbootin64?

Well, the PL011 chip is much more compatible with the original IBM PC UART. There are many properties that you simply cannot set with AUX UART, and there are missing features like detecting Break for example. Although raspbootin64 does not use these extra features, I thought it's better to give an example with the more capable device.

PS.: btw your raspbootin was a great inspiration! I've linked it on the tutorial, but I also would like to say a very very big thanks to you here! I've also implemented a PC BIOS version of the receiver part, see https://gitlab.com/bztsrc/imgrecv :-) (Please note that the RPi4 version of imgrecv hasn't been tested yet.)

Cheers,
bzt
