### ISSUE TITLE
The USBs ? | Keyboard

### ISSUE THREAD

**Issue by ajh123** [bztsrc/raspi3-tutorial#79]
@bztsrc 
Since this tutorial is just for the hardware . So is the pi's USBs . So how can we read from them?. e.g. Keyboards?

**Comment by bztsrc** [comment]
Hi,

Handling USB is a bit tricky. You have to write a driver for the HUD controller first (at MMIO 0x3F980000). Then you have to detect which HUBs and devices are connected to it. Then you have to write a HID driver for the keyboard.

I'd say the easiest way is to use an already written library (in C): https://github.com/Chadderz121/csud
A port which is converted for the AArch64 can be found here: https://github.com/LdB-ECM/Raspberry-Pi/tree/master/Arm32_64_USB

Cheers,
bzt
