### ISSUE TITLE
How to tune the booting parameters of Lineage 16 for Raspi 3 to boot it with qemu / kvm on the Jetson nano...

### ISSUE THREAD

**Issue by Marietto2008** [bztsrc/raspi3-tutorial#88]
Hello.

I would like to emulate this version of Android,called "Konstakang",that u can find here :

https://konstakang.com/devices/rpi3/LineageOS16.0/

with qemu and kvm on my jetson nano (arm64). I'm reading that it can be done,according with these repos :

https://github.com/wimvanderbauwhede/limited-systems/wiki/Raspbian-%22stretch%22-for-Raspberry-Pi-3-on-QEMU

https://github.com/dhruvvyas90/qemu-rpi-kernel

https://www.linuxquestions.org/questions/linux-newbie-8/trying-to-emulate-raspberrypi3-using-qemu-4175629475/

https://github.com/bztsrc/raspi3-tutorial

In particular the last website suggested to do something like this :

```
qemu-system-aarch64 -M raspi3 -m 1G \

-serial stdio -kernel /home/zi/Desktop/Work/I9/Android/lineage/Konsta-rpi3/boot/zImage \

-hda /home/zi/Desktop/Work/I9/Android/lineage/Konsta-rpi3/boot/ramdisk.img \

-append "console=ttyS0,38400 root=/dev/mmcblk0p2 rootfstype=ext4 rw vt.global_cursor_default=0 androidboot.selinux=permissive debug drm.debug=0" \

-dtb /home/zi/Desktop/Work/I9/Android/lineage/Konsta-rpi3/boot/bcm2710-rpi-3-b.dtb \

-cpu cortex-a53


```
= black screen

This is the config.txt file included inside the Lineage 16 package :

```
# Kernel

kernel=zImage


# Ramdisk

gpio=21=ip,pu

[gpio21=1]

initramfs ramdisk.img followkernel

[gpio21=0]

initramfs ramdisk-recovery.img followkernel

[all]


# Audio

dtparam=audio=on

#audio_pwm_mode=2

#disable_audio_dither=1

hdmi_force_edid_audio=1

#hdmi_ignore_edid_audio=1


# Audio DAC

#dtoverlay=hifiberry-dacplus


# Camera

gpu_mem=128

start_x=1


# Display

hdmi_force_hotplug=1

hdmi_drive=2

hdmi_group=1

hdmi_mode=4

disable_overscan=1


# Graphics acceleration

[gpio21=1]

#dtoverlay=vc4-fkms-v3d,cma-256

dtoverlay=vc4-kms-v3d,cma-256

mask_gpu_interrupt0=0x400

[all]


# I2C

dtparam=i2c_arm=on


# I2S

#dtparam=i2s=on


# IR

#dtoverlay=gpio-ir,gpio_pin=18


# Keys

#dtoverlay=gpio-key,gpio=21,keycode=116,label="POWER"


# RPI display/touchscreen

dtoverlay=rpi-backlight

dtoverlay=rpi-ft5406


# RTC

#dtoverlay=i2c-rtc,ds3231


# Serial console

enable_uart=1


# SPI

dtparam=spi=on


# Waveshare touchscreen

#dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900
```

**Comment by bztsrc** [comment]
Hi,

> I would like to emulate this version of Android

Sorry, this tutorial is about bare metal programming, and not about Android. I've never tried to run Android on qemu, so I don't know the answer.

You should be able to get more help on the qemu or Linage forums I guess.

Cheers,
bzt
