### ISSUE TITLE
qemu emulation not working

### ISSUE THREAD

**Issue by ozbenh** [bztsrc/raspi3-tutorial#97]
Hi !

I've tried qemu 5.2 and 6.1 and I cant' seem to get anything either on the framebuffer or the serial port with kernel8 from the current raspios (2021-05-07). I can get 32-bit kernel7 to boot with qemu-system-arm emulating a rpi2, but I had 0 luck so far with anything 64-bit. Are you aware of a known issue in that area ?

**Comment by ozbenh** [comment]
Bah, I got serial working, it's the framebuffer that broke with recent kernels (work with an older raspbian one)

**Comment by ozbenh** [comment]
I sent a couple of patches to the qemu-devel list to fix the problem. Closing the issue.

**Comment by cedric-dufour** [comment]
Sorry for intruding. Is there a way to _work around_ this bug (using the latest kernel and expecting only a working serial console) ?
(I followed your submission/discussion on qemu-devel but it's above my abilities to find any hint in that direction)

**Comment by ozbenh** [comment]
I'm pretty sure I did get it working with serial, that said, I don't remember how and I'm away from the machine where that stuff is for the next couple of weeks...

**Comment by bztsrc** [comment]
Huh, mea culpa, I haven't noticed this issue until now.

> Are you aware of a known issue in that area ?

Nothing that I know of. But I haven't used it for a while, I'm occupied with other projects lately.

I did a quick test now, and serial works for me with the latest qemu on my distro (both 03_uart1 and 05_uart1 examples runs fine, qemu version 6.1.0-5). On the other hand I can confirm that 09_framebuffer doesn't work any more.

> Bah, I got serial working

Ok, good to hear!

> I sent a couple of patches to the qemu-devel list to fix the problem.

Thanks! Reading through the mails I have a feeling that adding raspi4 introduced a bug and broke machine raspi3.

Cheers,
bzt
